### ISSUE TITLE
Unable to import aespython module

### ISSUE THREAD

**Issue by SecurityOps404** [HardCorePawn/extract_mbc_keys#1]
Hi There, 
  While trying to run this script it gives me the error cannot import aespython. I did some looking and was unable to find where this module can be installed from. I installed pycrypto and pycryptodome thinking aespython was in those, but it didn't work.

**Comment by HardCorePawn** [comment]
Seems I may have forgotten to include the library properly when I was packing this up and uploading it? ??? oops!

You can see the "aespython" folder with the necessary files in it from the gurnec's repo (which this script is based on) here: https://github.com/gurnec/decrypt_bitcoinj_seed

I've added the "aespython" folder to my repo... try redownloading the latest code and trying again. 

Should be fixed by: https://github.com/HardCorePawn/extract_mbc_keys/commit/594dbf1a5b8a0e2ef784c5886874ab2ca014f30a

**Comment by SecurityOps404** [comment]
Awesome. I did notice the aespython folder afterwards and downloaded it. My bad. I was just taking the py scripts and running them without getting the whole repo. Thanks! I have a separate issue now. I still need to recover the password. I'm running btcrecover but have yet to have any luck.
